server.port=8080

logging.level.org.springframework.security = DEBUG
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_Gg0FvfHmB

spring.application.name=gatewayfinal-service

orders.service.url=${ORDERS_SERVICE_URL:http://localhost:8081}
payments.service.url=${PAYMENTS_SERVICE_URL:http://localhost:8082}

spring.cloud.gateway.routes[0].id=orderservice
spring.cloud.gateway.routes[0].uri=${orders.service.url}
spring.cloud.gateway.routes[0].predicates[0]=Path=/orders/**

spring.cloud.gateway.routes[1].id=payment-service
spring.cloud.gateway.routes[1].uri=${payments.service.url}
spring.cloud.gateway.routes[1].predicates[0]=Path=/payments/**
