server.port=8080

logging.level.org.springframework.security = DEBUG
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_gmNWvI7Th

spring.application.name=gatewayfinal-service

spring.cloud.gateway.routes[0].id=orderservice
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/orders/**

spring.cloud.gateway.routes[1].id=payment-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/payments/**
